# Generated by Django 2.2.1 on 2020-08-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=26)),
                ('Description', models.TextField(max_length=248)),
                ('Population', models.IntegerField()),
                ('GDP', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=26)),
                ('Description', models.TextField(max_length=248)),
                ('Population', models.IntegerField()),
                ('GDP', models.FloatField()),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=26)),
                ('Description', models.TextField(max_length=248)),
                ('Population', models.IntegerField()),
                ('GDP', models.FloatField()),
                ('PinCode', models.CharField(max_length=6)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Country')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.State')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=26)),
                ('Description', models.TextField(max_length=248)),
                ('Population', models.IntegerField()),
                ('GDP', models.FloatField()),
                ('PinCode', models.CharField(max_length=6)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Country')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.State')),
            ],
        ),
    ]
