# Generated by Django 2.2.1 on 2020-08-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200803_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='City',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='details.City'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Town',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='details.Town'),
        ),
    ]
