# Generated by Django 2.2.1 on 2020-08-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20200803_0849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
