# Generated by Django 2.2.1 on 2020-08-03 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=26)),
                ('City', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='details.City')),
                ('Town', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='details.Town')),
            ],
        ),
    ]
